name: Weekly Daytona Issues Analysis

on:
  schedule:
    - cron: '0 7 * * 1' # Run every Monday at 07:00 UTC (which is 08:00 CET)
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run analysis script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python daytona_issues.py
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: analysis-results
        path: |
          artifact/*.txt
          artifact/*.png
          github_data.json